package com.trimtime.appointment;

import com.trimtime.identity.*; import com.trimtime.barber.*; import com.trimtime.slots.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*;

@Service public class AppointmentService { private static final List<AppointmentStatus> BLOCKING=List.of(AppointmentStatus.CONFIRMED,AppointmentStatus.IN_PROGRESS); private final UserAccountRepository users; private final BarberMembershipRepository memberships; private final AppointmentRepository appointments; private final SlotService slots;
 public AppointmentService(UserAccountRepository users,BarberMembershipRepository memberships,AppointmentRepository appointments,SlotService slots){this.users=users;this.memberships=memberships;this.appointments=appointments;this.slots=slots;}
 @Transactional public Appointment book(Long customerId,AppointmentDtos.CreateRequest input){var customer=users.findById(customerId).orElseThrow();var serviceIds=input.selectedServiceIds();var selection=slots.resolve(input.salonId(),serviceIds,input.addonIds());var start=LocalDateTime.of(input.date(),input.startTime());if(start.isBefore(LocalDateTime.now()))throw new InvalidBookingTimeException();var end=start.plusMinutes(selection.duration());var eligible=slots.eligible(input.salonId(),serviceIds,input.date(),input.startTime(),end.toLocalTime());if(eligible.isEmpty())throw new NoBarberAvailableException();eligible.sort(Comparator.comparing(m->m.getBarber().getDisplayName()));for(var candidate:eligible){var locked=memberships.findByIdForUpdate(candidate.getId()).orElseThrow(NoBarberAvailableException::new);if(slots.free(locked.getBarber().getId(),start,end))return appointments.save(new Appointment(customer,selection.salon(),locked.getBarber(),start,end,selection.serviceSummary(),selection.addonSummary(),selection.duration(),selection.price()));}throw new NoBarberAvailableException();}
 @Transactional(readOnly=true) public List<Appointment> mine(Long customerId){return appointments.findByCustomerIdOrderByStartAtDesc(customerId);}
 public static class InvalidBookingTimeException extends RuntimeException{} public static class NoBarberAvailableException extends RuntimeException{}
}
