package com.trimtime.barber;
import com.trimtime.identity.*; import com.trimtime.salon.*; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service public class BarberService {
 private final UserAccountRepository users; private final SalonRepository salons; private final BarberJoinRequestRepository requests; private final BarberMembershipRepository memberships; private final JdbcTemplate jdbc;
 public BarberService(UserAccountRepository users,SalonRepository salons,BarberJoinRequestRepository requests,BarberMembershipRepository memberships,JdbcTemplate jdbc){this.users=users;this.salons=salons;this.requests=requests;this.memberships=memberships;this.jdbc=jdbc;}
 @Transactional public BarberJoinRequest apply(Long barberId,Long salonId,BarberDtos.ApplyRequest input){var barber=users.findById(barberId).orElseThrow(UnknownUserException::new); var salon=salons.findById(salonId).orElseThrow(SalonMissingException::new); if(salons.findByOwnerId(barberId).map(Salon::getId).filter(salonId::equals).isPresent()) throw new InvalidOnboardingException("A salon owner cannot request to join their own salon"); if(memberships.existsByBarberId(barberId)) throw new AlreadyMemberException(); if(requests.findByBarberIdAndSalonIdAndStatus(barberId,salonId,BarberStatus.PENDING).isPresent()) throw new PendingRequestException(); jdbc.update("INSERT INTO barber_profiles (user_id, bio, experience_years) VALUES (?, ?, ?) ON DUPLICATE KEY UPDATE bio = VALUES(bio), experience_years = VALUES(experience_years)",barberId,input.bio()==null?"":input.bio(),input.experienceYears()==null?0:input.experienceYears()); return requests.save(new BarberJoinRequest(barber,salon,input.message()==null?"":input.message())); }
 @Transactional(readOnly=true) public List<BarberJoinRequest> mine(Long barberId){return requests.findByBarberIdOrderByCreatedAtDesc(barberId);}
 @Transactional(readOnly=true) public List<BarberJoinRequest> forOwner(Long ownerId){var salon=salons.findByOwnerId(ownerId).orElseThrow(SalonMissingException::new);return requests.findBySalonIdAndStatusOrderByCreatedAtAsc(salon.getId(),BarberStatus.PENDING);}
 @Transactional public BarberMembership decide(Long ownerId,Long requestId,boolean approve){var owner=users.findById(ownerId).orElseThrow(UnknownUserException::new);var salon=salons.findByOwnerId(ownerId).orElseThrow(SalonMissingException::new);var request=requests.findById(requestId).orElseThrow(RequestMissingException::new);if(!request.getSalon().getId().equals(salon.getId()))throw new ForbiddenDecisionException();if(request.getStatus()!=BarberStatus.PENDING)throw new RequestAlreadyDecidedException();if(!approve){request.decide(BarberStatus.REJECTED);return null;}if(memberships.existsByBarberId(request.getBarber().getId()))throw new AlreadyMemberException();request.decide(BarberStatus.APPROVED);request.getBarber().addRole(Role.BARBER);return memberships.save(new BarberMembership(request.getBarber(),salon,owner));}
 public static class UnknownUserException extends RuntimeException{} public static class SalonMissingException extends RuntimeException{} public static class RequestMissingException extends RuntimeException{} public static class PendingRequestException extends RuntimeException{} public static class AlreadyMemberException extends RuntimeException{} public static class InvalidOnboardingException extends RuntimeException{public InvalidOnboardingException(String m){super(m);}} public static class ForbiddenDecisionException extends RuntimeException{} public static class RequestAlreadyDecidedException extends RuntimeException{}
}
