package com.trimtime.barber;
import jakarta.validation.Valid; import org.springframework.http.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.security.core.context.SecurityContextHolder; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api") public class BarberController {
 private final BarberService service; private final BarberQualificationService qualificationService; public BarberController(BarberService service, BarberQualificationService qualificationService){this.service=service;this.qualificationService=qualificationService;}
 private Long current(){return ((com.trimtime.identity.SessionAuthenticationFilter.UserPrincipal)SecurityContextHolder.getContext().getAuthentication().getPrincipal()).id();}
 @PostMapping("/barber/applications/{salonId}") public ResponseEntity<BarberDtos.RequestResponse> apply(@PathVariable Long salonId,@Valid @RequestBody BarberDtos.ApplyRequest request){return ResponseEntity.status(HttpStatus.CREATED).body(BarberDtos.RequestResponse.from(service.apply(current(),salonId,request)));}
 @GetMapping("/barber/applications/mine") public List<BarberDtos.RequestResponse> mine(){return service.mine(current()).stream().map(BarberDtos.RequestResponse::from).toList();}
 @PreAuthorize("hasRole('SALON_OWNER')") @GetMapping("/salons/mine/barber-applications") public List<BarberDtos.RequestResponse> ownerApplications(){return service.forOwner(current()).stream().map(BarberDtos.RequestResponse::from).toList();}
 @PreAuthorize("hasRole('SALON_OWNER')") @PostMapping("/salons/mine/barber-applications/{requestId}/approve") public ResponseEntity<BarberDtos.MembershipResponse> approve(@PathVariable Long requestId){return ResponseEntity.status(HttpStatus.CREATED).body(BarberDtos.MembershipResponse.from(service.decide(current(),requestId,true)));}
 @PreAuthorize("hasRole('SALON_OWNER')") @PostMapping("/salons/mine/barber-applications/{requestId}/reject") public ResponseEntity<Void> reject(@PathVariable Long requestId){service.decide(current(),requestId,false);return ResponseEntity.noContent().build();}
 @PreAuthorize("hasRole('SALON_OWNER')") @GetMapping("/salons/mine/barbers") public List<BarberQualificationDtos.BarberResponse> barbers(){return qualificationService.list(current());}
 @PostMapping("/barber/applications/{requestId}/withdraw") public BarberDtos.RequestResponse withdraw(@PathVariable Long requestId){return BarberDtos.RequestResponse.from(service.withdraw(current(),requestId));}
 @PreAuthorize("hasRole('SALON_OWNER')") @PostMapping("/salons/mine/barbers/enroll-self") public ResponseEntity<BarberDtos.MembershipResponse> enrollSelf(@Valid @RequestBody(required=false) BarberDtos.SelfEnrollRequest input){return ResponseEntity.status(HttpStatus.CREATED).body(BarberDtos.MembershipResponse.from(service.enrollOwner(current(),input)));}
 @PreAuthorize("hasRole('SALON_OWNER')") @DeleteMapping("/salons/mine/barbers/{barberId}") public ResponseEntity<Void> deactivateBarber(@PathVariable Long barberId){service.deactivateBarber(current(),barberId);return ResponseEntity.noContent().build();}
 @PreAuthorize("hasRole('BARBER')") @DeleteMapping("/barber/membership") public ResponseEntity<Void> leave(){service.leaveSalon(current());return ResponseEntity.noContent().build();}
 @PreAuthorize("hasRole('BARBER')") @PostMapping("/barber/membership/leave") public ResponseEntity<Void> leavePost(){service.leaveSalon(current());return ResponseEntity.noContent().build();}
 @PreAuthorize("hasRole('SALON_OWNER')") @PutMapping("/salons/mine/barbers/{barberId}/services") public BarberQualificationDtos.BarberResponse services(@PathVariable Long barberId,@Valid @RequestBody BarberQualificationDtos.UpdateRequest input){return qualificationService.update(current(),barberId,input);}
}
