CREATE TABLE appointments (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    booking_reference VARCHAR(36) NOT NULL,
    customer_user_id BIGINT NOT NULL,
    salon_id BIGINT NOT NULL,
    barber_user_id BIGINT NOT NULL,
    start_at DATETIME NOT NULL,
    end_at DATETIME NOT NULL,
    status VARCHAR(24) NOT NULL,
    service_name VARCHAR(160) NOT NULL,
    addon_summary VARCHAR(2000),
    duration_minutes INT NOT NULL,
    total_price DECIMAL(10,2) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_appointments_reference UNIQUE (booking_reference),
    CONSTRAINT fk_appointments_customer FOREIGN KEY (customer_user_id) REFERENCES users(id),
    CONSTRAINT fk_appointments_salon FOREIGN KEY (salon_id) REFERENCES salons(id),
    CONSTRAINT fk_appointments_barber FOREIGN KEY (barber_user_id) REFERENCES users(id),
    CONSTRAINT chk_appointments_time CHECK (start_at < end_at),
    CONSTRAINT chk_appointments_duration CHECK (duration_minutes > 0),
    CONSTRAINT chk_appointments_price CHECK (total_price >= 0),
    INDEX ix_appointments_barber_time (barber_user_id, start_at, end_at),
    INDEX ix_appointments_customer_time (customer_user_id, start_at)
) ENGINE=InnoDB;
