package com.trimtime.availability;
import com.trimtime.identity.*; import com.trimtime.barber.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*;
@Service public class AvailabilityService {private final UserAccountRepository users; private final BarberMembershipRepository memberships; private final WorkingHourRepository hours; private final DayOffRepository days;
 public AvailabilityService(UserAccountRepository users,BarberMembershipRepository memberships,WorkingHourRepository hours,DayOffRepository days){this.users=users;this.memberships=memberships;this.hours=hours;this.days=days;}
 private UserAccount barber(Long id){if(!memberships.existsByBarberId(id))throw new MembershipRequiredException();return users.findById(id).orElseThrow();}
 private LocalDate monday(LocalDate date){return date.with(java.time.DayOfWeek.MONDAY);}
 @Transactional(readOnly=true) public List<WorkingHour> getHours(Long id,LocalDate weekStart){barber(id);return hours.findByBarberIdAndWeekStartDateOrderByDayOfWeekAsc(id,monday(weekStart));} @Transactional(readOnly=true) public List<DayOff> getDays(Long id){barber(id);return days.findByBarberIdAndDateGreaterThanEqualOrderByDateAsc(id,LocalDate.now());}
 @Transactional public WorkingHour saveHour(Long id,AvailabilityDtos.HourRequest input){var user=barber(id);if(input.weekStartDate().getDayOfWeek()!=java.time.DayOfWeek.MONDAY||!input.startTime().isBefore(input.endTime()))throw new InvalidHoursException();var week=monday(input.weekStartDate());var h=hours.findByBarberIdAndWeekStartDateAndDayOfWeek(id,week,input.dayOfWeek()).orElseGet(()->new WorkingHour(user,week,input.dayOfWeek(),input.startTime(),input.endTime()));h.setTimes(input.startTime(),input.endTime());return hours.save(h);}
 @Transactional public List<WorkingHour> saveHours(Long id,AvailabilityDtos.BulkHourRequest input){barber(id);if(input.weekStartDate().getDayOfWeek()!=java.time.DayOfWeek.MONDAY||!input.startTime().isBefore(input.endTime())||input.daysOfWeek().stream().distinct().count()!=input.daysOfWeek().size())throw new InvalidHoursException();return input.daysOfWeek().stream().map(day->saveHour(id,new AvailabilityDtos.HourRequest(day,input.weekStartDate(),input.startTime(),input.endTime()))).toList();}
 @Transactional public DayOff addDay(Long id,AvailabilityDtos.DayOffRequest input){if((input.startTime()==null)!=(input.endTime()==null)||input.startTime()!=null&&!input.startTime().isBefore(input.endTime()))throw new InvalidHoursException();if(!hours.existsByBarberIdAndWeekStartDateAndDayOfWeek(id,monday(input.date()),input.date().getDayOfWeek().getValue()))throw new SpecialDateNotWorkingException();return days.save(new DayOff(barber(id),input.date(),input.startTime(),input.endTime(),input.reason()));} @Transactional public void removeDay(Long id,Long dayId){barber(id);days.findByIdAndBarberId(dayId,id).orElseThrow(DayOffMissingException::new);days.deleteById(dayId);}
 public static class MembershipRequiredException extends RuntimeException{} public static class InvalidHoursException extends RuntimeException{} public static class SpecialDateNotWorkingException extends RuntimeException{} public static class DayOffMissingException extends RuntimeException{}
}
